/**
 * Mock API server for nail admin-ops
 * Serves /api/* endpoints on port 4173 using real generated simulation data
 */
const express = require('express')
const path = require('path')
const fs = require('fs')
const Database = require('better-sqlite3')

const app = express()
const PORT = 4173
const DATA_DIR = path.join(__dirname, '../data/xhs/processed')
const SIM_DIR = path.join(__dirname, '../user-client/outputs/simulation')
const DB_PATH = path.join(__dirname, 'styles.db')

// Open SQLite (shared connection, WAL mode for concurrent reads)
const stylesDb = new Database(DB_PATH)
stylesDb.pragma('journal_mode = WAL')

// recommend_slots 表结构已在 init-styles-db.js 中管理，此处不再重建

// ── 启动时把 weekly CSV 最新一周的分数同步到 styles.db ──────────────
;(function syncWeeklyScores() {
  const csvPath = path.join(SIM_DIR, 'xhs_simulated_nail_style_weekly_metrics.csv')
  if (!fs.existsSync(csvPath)) { console.warn('[sync] weekly CSV 不存在，跳过分数同步'); return }

  const lines = fs.readFileSync(csvPath, 'utf-8').replace(/^﻿/, '').split('\n').filter(Boolean)
  const header = lines[0].split(',')
  const col = (name) => header.indexOf(name)

  // 找最新 week_idx
  let maxWeek = -1
  for (let i = 1; i < lines.length; i++) {
    const w = parseInt(lines[i].split(',')[col('week_idx')])
    if (w > maxWeek) maxWeek = w
  }

  // 取最新一周每款数据
  const latest = {}
  for (let i = 1; i < lines.length; i++) {
    const vals = lines[i].split(',')
    if (parseInt(vals[col('week_idx')]) !== maxWeek) continue
    latest[vals[col('style_id')]] = {
      hot_score:        parseFloat(vals[col('hot_score')]),
      cold_risk_score:  parseFloat(vals[col('cold_risk_score')]),
      growth_score:     parseFloat(vals[col('growth_score')]),
    }
  }

  const update = stylesDb.prepare(`
    UPDATE styles SET hot_score=?, cold_risk_score=?, growth_score=?, updated_at=datetime('now')
    WHERE id=?
  `)
  const sync = stylesDb.transaction(() => {
    let n = 0
    for (const [id, scores] of Object.entries(latest)) {
      const r = update.run(scores.hot_score, scores.cold_risk_score, scores.growth_score, id)
      if (r.changes) n++
    }
    return n
  })
  const synced = sync()
  console.log(`[sync] weekly week=${maxWeek} → styles.db 已同步 ${synced} 款 hot/cold/growth 分数`)
})()

// 审计日志表
stylesDb.exec(`
  CREATE TABLE IF NOT EXISTS audit_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    op          TEXT NOT NULL,
    params      TEXT,
    result      TEXT,
    created_at  TEXT DEFAULT (datetime('now'))
  );
`)

function auditLog(op, params, result) {
  stylesDb.prepare(`INSERT INTO audit_log (op, params, result) VALUES (?, ?, ?)`)
    .run(op, JSON.stringify(params), JSON.stringify(result))
}
const IMAGES_DIR = path.join(DATA_DIR, 'images')

function loadJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf-8'))
}

// CORS
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*')
  next()
})

// Serve nail images
app.get('/api/xhs-image', (req, res) => {
  const file = req.query.file
  if (!file || file.includes('..')) return res.status(400).end()
  const imgPath = path.join(IMAGES_DIR, file)
  if (!fs.existsSync(imgPath)) return res.status(404).end()
  res.sendFile(imgPath)
})

// /api/xhs-style-dataset — enriched dataset with recommendBucket, hotScore, etc.
app.get('/api/xhs-style-dataset', (req, res) => {
  res.json(loadJson(path.join(DATA_DIR, 'xhs-style-dataset.enriched.json')))
})

// /api/xhs-trend-snapshot — generated by build_xhs_operational_mock.py
app.get('/api/xhs-trend-snapshot', (req, res) => {
  res.json(loadJson(path.join(SIM_DIR, 'xhs_trend_snapshot.json')))
})

// /api/simulation-summary — generated xhs_summary.json (top_hot/cold/potential + model report)
app.get('/api/simulation-summary', (req, res) => {
  res.json(loadJson(path.join(SIM_DIR, 'xhs_summary.json')))
})

// /api/xhs-trend-overview — lightweight list used by trending page
// Joins xhs_summary top lists with enriched dataset for name/image
app.get('/api/xhs-trend-overview', (req, res) => {
  const summary = loadJson(path.join(SIM_DIR, 'xhs_summary.json'))
  const dataset = loadJson(path.join(DATA_DIR, 'xhs-style-dataset.enriched.json'))
  const styleMap = new Map(dataset.styles.map(s => [s.id, s]))

  function enrich(row, type) {
    const s = styleMap.get(row.style_id) || {}
    return {
      id: row.style_id,
      name: s.name || s.rawTitle || row.style_id,
      image: s.image || '',
      category: s.primaryTag || row.category || '精选',
      confirmCount: row.total_confirm_uv || 0,
      hotIndex: Math.round((row.hot_score || 0) * 100),
      wantCount: row.want_uv || 0,
      growthScore: Math.round((row.growth_score || 0) * 100),
      viewCount: row.view_uv || 0,
      tryOnCount: row.tryon_uv || 0,
      coldRisk: Math.round((row.cold_risk_score || 0) * 100)
    }
  }

  res.json({
    hotStyles: (summary.top_hot || []).slice(0, 16).map(r => enrich(r, 'hot')),
    potentialStyles: (summary.top_potential || []).slice(0, 12).map(r => enrich(r, 'potential')),
    coldStyles: (summary.top_cold || []).slice(0, 12).map(r => enrich(r, 'cold'))
  })
})

// /api/metrics-summary — aggregated totals derived from xhs_summary
app.get('/api/metrics-summary', (req, res) => {
  const summary = loadJson(path.join(SIM_DIR, 'xhs_summary.json'))
  const dataset = loadJson(path.join(DATA_DIR, 'xhs-style-dataset.enriched.json'))
  const styleMap = new Map(dataset.styles.map(s => [s.id, s]))

  const allRows = [...(summary.top_hot || []), ...(summary.top_potential || []), ...(summary.top_cold || [])]
  let tryOns = 0, views = 0, wants = 0, confirms = 0
  allRows.forEach(r => {
    views += r.view_uv || 0
    tryOns += r.tryon_uv || 0
    wants += r.want_uv || 0
    confirms += r.total_confirm_uv || 0
  })

  const tryonConfirmRate = tryOns ? confirms / tryOns : 0
  const totalConfirmRate = views ? confirms / views : 0

  res.json({
    totals: {
      exposures: Math.round(views * 1.4),
      views,
      candidates: Math.round(views * 0.55),
      try_ons: tryOns,
      try_on_users: Math.round(tryOns * 0.58),
      result_views: Math.round(tryOns * 0.9),
      intents: wants,
      orders: confirms,
      candidate_rate: 0.55,
      tryon_confirm_rate: tryonConfirmRate,
      total_confirm_rate: totalConfirmRate,
      intent_to_order_rate: wants ? confirms / wants : 0
    },
    styles: allRows.slice(0, 20).map(r => ({
      style_id: r.style_id,
      label: r.label || r.true_state || 'Stable',
      exposures: r.view_uv || 0,
      orders: r.total_confirm_uv || 0,
      booking_rate: r.tryon_confirm_rate || 0,
      intent_rate: r.want_uv && r.view_uv ? r.want_uv / r.view_uv : 0
    })),
    recent_events: dataset.styles.slice(0, 8).map((s, i) => ({
      id: i + 1,
      user_id: `user_${1000 + i}`,
      style_id: s.id,
      event_type: i % 3 === 0 ? 'tryon_start' : i % 3 === 1 ? 'want_added' : 'confirm_order',
      created_at: new Date(Date.now() - i * 3600000).toISOString()
    }))
  })
})

// /api/ops-deepseek-chat — proxy to DeepSeek API
// 读取 DeepSeek API Key：优先读 deepseek-key.txt，其次读 .env，最后读环境变量
function readKeyTxt(txtPath) {
  try {
    const val = fs.readFileSync(txtPath, 'utf-8').trim()
    if (val && !val.startsWith('#') && val !== '在此填写你的DeepSeek API Key') return val
  } catch { }
  return ''
}
function loadEnv(envPath) {
  try {
    return fs.readFileSync(envPath, 'utf-8').split('\n').reduce((acc, line) => {
      const m = line.match(/^(\w+)\s*=\s*"?([^"]*)"?$/)
      if (m) acc[m[1]] = m[2]
      return acc
    }, {})
  } catch { return {} }
}
const KEY_TXT = path.join(__dirname, '../user-client/deepseek-key.txt')
const env = loadEnv(path.join(__dirname, '../user-client/.env'))
const DEEPSEEK_API_KEY = readKeyTxt(KEY_TXT) || env.DEEPSEEK_API_KEY || process.env.DEEPSEEK_API_KEY || ''
const DEEPSEEK_BASE_URL = env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com'

app.use(express.json())

// ── Prompt 构建 ─────────────────────────────────────────────────────────────

const CHAT_SYSTEM = `你是一个美甲门店的 AI 运营助手，现在处于【对话模式】。
用户可能随便聊：美甲趋势、风格建议、文案创作、行业知识等。
规则：
- 语气轻松自然，不强行套数据分析框架
- 给出专业美甲行业建议，但不需要引用具体指标
- 如果用户问到具体数据（某款热度、冷门风险等），提示可切换到【洞察模式】
- 回复简洁，不生成长篇报告`

const INSIGHT_SYSTEM = `你是一个美甲门店的 AI 运营助手，现在处于【洞察模式】。
系统已注入当前运营聚合数据，请基于这些数据给出精准分析。
规则：
- 每个结论必须引用具体指标（hot_score、cold_risk_score、试戴量、确认率等）
- 输出优先用表格或分点列举，便于快速读取
- 分析要带行动建议，但不直接执行操作（执行需切换到【执行模式】）
- 样本不足或数据异常时必须明确说明，不得捏造结论`

// ── ACTION 模式静态层（schema + catalog + 链式规则，不含任何运行时数据）──────
const ACTION_STATIC = `你是美甲门店 AI 运营助手，现在处于【执行模式】。

## 输出格式
用户每次发出操作指令，你必须返回一个纯 JSON 对象（不加任何 markdown 代码块）：
{
  "reply": "自然语言说明你的分析和操作计划（必填）",
  "ops": [
    { "opId": "操作ID", "params": {...}, "resultRef": "可选，存储查询结果的变量名", "reason": "执行理由" }
  ]
}
只问问题不执行时，ops 返回 []。

---

## 数据库 Schema

### styles 表（全库约 123 条，核心款式数据）

### 身份字段
| 字段 | 类型 | 说明 |
|------|------|------|
| id | TEXT PK | 款式唯一ID，格式 xhs-xxxxxxxx |
| name | TEXT | 款式名称，如"璀璨猫眼钻饰美甲" |
| style_code | TEXT | 运营编码，如 XHS0001 |
| description | TEXT | 运营文案描述 |
| author | TEXT | 创作者 |
| category | TEXT | 主分类，如"精选""猫眼""法式" |
| primary_tag / secondary_tag | TEXT | 一级/二级标签 |
| cover_image | TEXT | 封面图 URL |
| source_url | TEXT | 小红书原帖链接 |
| crawled | INTEGER | 1=已爬取（系统字段，只读） |
| thumb / accent / nail_gradient | TEXT | 封面主色/配色/渐变色（前端展示用，只读） |

### 运营状态（可写字段）
| 字段 | 类型 | 枚举值 / 说明 |
|------|------|---------------|
| status | TEXT | published / unpublished / archived |
| is_promoted | INTEGER | 1=主推 0=普通 |
| is_cold_start | INTEGER | 1=冷启动中 |
| recommend_bucket | TEXT | hot / potential / cold / stable |
| trend_label | TEXT | Hot / Potential / ColdDown / Stable |
| price | INTEGER | 元，通常 100-500 |
| makeable | INTEGER | 1=可制作 0=暂停 |
| listed_at | TEXT | 上架日期 YYYY-MM-DD |
| unpublished_at | TEXT | 最近下架时间 |

### 指标字段（可排序/筛选，均为数值）
| 字段 | 量级说明 |
|------|----------|
| hot_score | 0-1，>0.7 为热门 |
| cold_risk_score | 0-1，>0.6 为高风险 |
| growth_score | 0-1，>0.6 为快速增长 |
| view_uv | 曝光人数，百~万级 |
| tryon_uv | 试戴人数，十~千级 |
| want_uv | 收藏/想做人数 |
| confirm_uv | 确认要做人数 |
| tryon_confirm_rate | 0-1，试戴后确认率，均值约 0.15 |

### 小红书社交数据
| 字段 | 说明 |
|------|------|
| xhs_likes / xhs_saves / xhs_comments / xhs_shares | 点赞/收藏/评论/分享数 |

### 标签字段（JSON 数组字符串）
| 字段 | 可选值举例 |
|------|-----------|
| tags_style | ["简约","ins风","少女感",...] |
| tags_color | ["猫眼","手绘","渐变","法式","钻饰",...] |
| tags_season | ["春","夏","秋","冬"] |
| tags_shape | ["方形","圆形","尖形","杏形","超短"] |

### recommend_slots 表（固定8行，当前推荐位一轮）
| 字段 | 类型 | 说明 |
|------|------|------|
| position | INTEGER PK | 坑位序号 1-8，即展示顺序，不可变 |
| slot_type | TEXT | hot / potential / cold / adaptive，决定从哪个候选池选款 |
| style_id | TEXT FK→styles.id | 当前在位款式 ID，NULL=空坑 |
| strategy_id | TEXT | 生成本轮用的策略 ID |
| reason | TEXT | 选款理由（AI 填写或运营手动备注） |
| is_manual | INTEGER | 0=AI推荐，1=运营手动换款 |
| locked | INTEGER | 1=锁定（重新生成时跳过），0=可被覆盖 |
| updated_by | TEXT | 最后操作者：ai / operator / system |
| updated_at | TEXT | 最后更新时间 |

重新生成（recommend.generate）= 整批 upsert 覆盖未锁定行，locked=1 的行保持不变。
styleOffline=true 表示坑位款式已被下架，需要人工替换。

### recommend_strategies 表（5行，策略配置）
| 字段 | 类型 | 说明 |
|------|------|------|
| id | TEXT PK | hot_first / potential_up / cold_watch / adaptive_max / custom |
| name | TEXT | 展示名称 |
| slot_types | TEXT | JSON 数组，8个元素，每个为 hot/potential/cold/adaptive |

custom 行的 slot_types 可通过 recommend.generateCustom 随时覆盖写入。

### 候选池 Views（只读，status=published 已过滤）
| View | 排序 | 对应 slot_type |
|------|------|----------------|
| v_pool_hot | hot_score DESC | hot |
| v_pool_potential | growth_score DESC | potential |
| v_pool_cold | cold_risk_score DESC | cold |
| v_pool_adaptive | tryon_confirm_rate DESC | adaptive（基础兜底） |

兜底链：hot→potential→adaptive / potential→hot→adaptive / cold→adaptive / adaptive→hot

---

## 操作 Catalog（44个）

### 单条状态
| opId | 入参 | 返回 | 风险 |
|------|------|------|------|
| style.publish | { styleId, name } | { ok, id, status } | low |
| style.unpublish | { styleId, name } | { ok, id, status } | medium |
| style.archive | { styleId, name } | { ok, id, status } | high |

### 批量状态
| opId | 入参 | 返回 | 风险 |
|------|------|------|------|
| style.batchPublish | { ids: string[] } | { ok, affected, status } | medium |
| style.batchUnpublish | { ids: string[] } | { ok, affected, status } | medium |
| style.batchArchive | { ids: string[] } | { ok, affected, status } | high |
| style.batchSetBucket | { ids: string[], bucket: hot/potential/cold/stable } | { ok, affected } | medium |
| style.batchSetPromoted | { ids: string[], isPromoted: boolean } | { ok, affected } | low |

### 单条信息修改
| opId | 入参 | 返回 | 风险 |
|------|------|------|------|
| style.setPrice | { styleId, name, price: integer } | { ok, id } | low |
| style.setDescription | { styleId, name, description: string } | { ok, id } | low |
| style.setBucket | { styleId, name, bucket } | { ok, id } | low |
| style.setPromoted | { styleId, name, isPromoted: boolean } | { ok, id } | low |
| style.setCategory | { styleId, name, category: string } | { ok, id } | low |
| style.setTags | { styleId, name, tagField: tags_style/tags_color/tags_season/tags_shape, tags: string[] } | { ok, id } | low |

### 推荐位（P1-P8，8坑为一轮）
推荐位候选来源：只取 status=published 已上架款式
坑位类型：hot=热门(hot_score↓) / potential=潜力(growth_score↓) / cold=冷门观察(cold_risk_score↓) / adaptive=自适应(tryon_confirm_rate↓)
位置注意力：P1>P2>P3>P4>P5>P6>P7，P8=冷门观察位（流量最低）

| opId | 入参 | 返回 | 风险 |
|------|------|------|------|
| recommend.generate | { strategyId: hot_first/potential_up/cold_watch/adaptive_max/custom, intentText? } | { ok, generated[] } | medium |
| recommend.generateCustom | { slotTypes: string[8]（每个为hot/potential/cold/adaptive）, intentText? } | { ok, generated[] } | medium |
| recommend.set | { styleId, name, position: 1-8 } | { ok } | medium |
| recommend.clear | { position: 1-8 } | { ok } | low |
| recommend.clearAll | {} | { ok } | high — 清空全部8坑（保留类型配置） |
| recommend.swapPos | { positionA: 1-8, positionB: 1-8 } | { ok } | medium — 按位置号互换，运营看页面操作时用 |
| recommend.swapStyle | { styleIdA, styleIdB } | { ok, posA, posB } | medium — 按款式ID互换，自动找各自坑位；任一款不在推荐位则报错 |
| recommend.lock | { position: 1-8 } | { ok } | low |
| recommend.unlock | { position: 1-8 } | { ok } | low |
| recommend.batchLock | { positions: number[] } | { ok, locked[] } | low — 一次锁定多个位置，如"锁定前3位" |
| recommend.batchUnlock | { positions: number[] } | { ok, unlocked[] } | low |
| recommend.setSlotType | { position: 1-8, slotType: hot/potential/cold/adaptive } | { ok } | low |
| recommend.refreshSlot | { position: 1-8 } | { ok, oldStyleId, newStyleId } | low — 单坑重新从候选池选款（保持类型，跳过其他7坑已用款）；已锁定则报错 |
| recommend.fillEmpty | { intentText? } | { ok, filled[] } | low — 只填 style_id=NULL 的空坑，已有款式和锁定坑不动 |

重新生成会覆盖所有未锁定坑位；locked=1 的坑位 AI 生成时自动跳过。
swapPos vs swapStyle：用户说"第2位和第5位换一下"→ swapPos；用户说"把璀璨猫眼和法式渐变换一下"→ swapStyle。
fillEmpty vs generate：fillEmpty 增量补全（保留现有），generate 全量重写（跳过锁定）。

### 查询操作（只读，无需用户确认，直接执行）

返回格式说明：
- 大多数操作返回 { rows: [...], count: N }，可用 $ref 引用 rows 数组
- query.styleDetail 返回单个款式对象（无 rows 层）
- query.findStyleInSlots 返回 { found: bool, slot: {...} }（无 rows 层）
- query.stats 返回 { byStatus: [{status,n}], byBucket: [{recommend_bucket,n}], total: N }
- query.lockedSlots 返回 { rows: [...], lockedCount: N, lockedPositions: [1,3,...] }

| opId | 入参 | 返回字段 |
|------|------|----------|
| query.search | { filters: Filter[], sort?: {field, dir}, limit?: 1-200, fields?: string[] } | rows: 按 fields 决定；默认全量41字段 |
| query.styleDetail | { styleId } | 单对象，全部41字段（id, name, status, hot_score, cold_risk_score, growth_score, tryon_confirm_rate, recommend_bucket, price, category, tags_* 等） |
| query.hotRank | { limit?: default 10 } | rows: id, name, recommend_bucket, hot_score, cold_risk_score, tryon_uv, confirm_uv, tryon_confirm_rate, status |
| query.coldRisk | { threshold?: default 0.6, limit?: default 10 } | rows: id, name, recommend_bucket, hot_score, cold_risk_score, view_uv, tryon_uv, status |
| query.metricsRank | { metric, limit?, dir?: "desc" } | rows: id, name, status, recommend_bucket, [指定metric字段] |
| query.metrics | { styleId } | rows: id, name + 全指标字段 |
| query.priceRange | { minPrice?, maxPrice?, limit? } | rows: id, name, price, status, recommend_bucket |
| query.lowConversion | { threshold?: 0.1, limit?: 20 } | rows: id, name, status, tryon_uv, confirm_uv, tryon_confirm_rate, hot_score |
| query.byBucket | { bucket: hot/potential/cold/stable, limit? } | rows: 全量41字段 |
| query.stats | {} | { byStatus, byBucket, total } — 无 rows |
| query.recommendSlots | {} | rows: 8条按position升序，每条含 position, slot_type, style_id, name, hot_score, cold_risk_score, growth_score, tryon_confirm_rate, view_uv, tryon_uv, confirm_uv, locked(0/1), is_manual(0/1), recommend_bucket, status, price, category, styleOffline(bool) |
| query.recommendPool | { type: hot/potential/cold/adaptive, limit?: 10 } | rows: id, name, recommend_bucket, [对应分数字段], view_uv, tryon_confirm_rate（hot→hot_score, potential→growth_score, cold→cold_risk_score, adaptive→tryon_confirm_rate） |
| query.recommendStrategies | {} | rows: id, name, description, slot_types(string[8]) |
| query.findStyleInSlots | { styleId } | { found: bool, slot: {position, slot_type, locked, style_id, name} 或 null } |
| query.lockedSlots | {} | { rows: [{position,locked,slot_type,style_id,name}×8], lockedCount, lockedPositions } |
| query.auditLog | { limit?: 20 } | rows: id, op, params(object), result(object), created_at |

query.search Filter：{ field: 字段名, op: eq/ne/gt/lt/gte/lte/like/in, value }
query.metricsRank metric：hot_score / cold_risk_score / growth_score / view_uv / tryon_uv / want_uv / confirm_uv / tryon_confirm_rate / xhs_likes / xhs_saves / xhs_comments / xhs_shares / price

---

## 链式操作规则（先查后写）

写操作需要 styleId / ids 时，**禁止编造 ID**，必须先用查询操作获取，再用 \$ref 引用。

\$ref 格式：{ "\$ref": "变量名", "path": "rows", "map": "id" }
- path：查询结果中数组字段（统一为 "rows"）
- map：从每个元素提取的字段（通常为 "id"）

示例 A — 下架冷门风险最高的5款：
{ "ops": [
  { "opId": "query.coldRisk", "params": { "threshold": 0.5, "limit": 5 }, "resultRef": "coldItems", "reason": "查冷门款" },
  { "opId": "style.batchUnpublish", "params": { "ids": { "\$ref": "coldItems", "path": "rows", "map": "id" } }, "reason": "批量下架" }
]}

示例 B — 把猫眼款全部设为 hot 分组：
{ "ops": [
  { "opId": "query.search", "params": { "filters": [{"field":"name","op":"like","value":"猫眼"}], "limit": 30 }, "resultRef": "catEye", "reason": "查猫眼款" },
  { "opId": "style.batchSetBucket", "params": { "ids": { "\$ref": "catEye", "path": "rows", "map": "id" }, "bucket": "hot" }, "reason": "标记为热门分组" }
]}

示例 C — 把增长分最高的3款放入推荐位 P6-P8（多步写操作）：
{ "ops": [
  { "opId": "query.metricsRank", "params": { "metric": "growth_score", "limit": 3 }, "resultRef": "rising", "reason": "查增长最快款" },
  { "opId": "recommend.set", "params": { "styleId": { "\$ref": "rising", "path": "rows[0]", "map": "id" }, "position": 6 }, "reason": "..." },
  ...
]}

注意：查询步骤用 "resultRef":"变量名" 存储，写步骤用 \$ref 引用；两步之间系统自动传递，不需要用户介入。

## 条件字段

ops 中每一步可携带 condition，系统在执行该步前先求值，不满足则跳过（不中断后续步骤）：

\`\`\`
"condition": { "$ref": "结果变量", "path": "rows.0.hot_score", "op": "gt", "value": 0.8 }
\`\`\`

op 可选：gt / gte / lt / lte / eq / ne
path 按点路径取值：rows 按 position 升序，rows.0 = P1，rows.1 = P2，以此类推。

---

## 执行规则
1. 写操作 ids/styleId 必须来自 \$ref，禁止字面量 ID（你不知道真实ID）
2. 高风险操作（archive/batchArchive）必须在 reply 中说明影响款式和范围
3. 只返回纯 JSON，不加任何 markdown 代码块
4. 只问问题不执行时 ops 为 []`

// ── 动态聚合上下文（纯数字，不含ID，所有模式共用）────────────────────────
function buildAggContext() {
  const byStatus = stylesDb.prepare(`SELECT status, COUNT(*) as n FROM styles GROUP BY status`).all()
  const byBucket = stylesDb.prepare(`SELECT recommend_bucket, COUNT(*) as n FROM styles GROUP BY recommend_bucket`).all()
  const metrics = stylesDb.prepare(`
    SELECT COUNT(*) as total,
      ROUND(AVG(hot_score),3) as avg_hot,
      ROUND(AVG(cold_risk_score),3) as avg_cold,
      ROUND(AVG(tryon_confirm_rate),3) as avg_conv,
      SUM(view_uv) as total_view,
      SUM(tryon_uv) as total_tryon,
      SUM(confirm_uv) as total_confirm
    FROM styles WHERE status='published'
  `).get()
  const slots = stylesDb.prepare(`
    SELECT rs.position, s.name as styleName, s.hot_score
    FROM recommend_slots rs LEFT JOIN styles s ON rs.style_id = s.id
    ORDER BY rs.position
  `).all()

  const statusMap = Object.fromEntries(byStatus.map(r => [r.status, r.n]))
  const bucketMap = Object.fromEntries(byBucket.map(r => [r.recommend_bucket, r.n]))

  return `
【当前运营快照】
- 款式库存：上架 ${statusMap.published || 0} / 下架 ${statusMap.unpublished || 0} / 归档 ${statusMap.archived || 0}
- 热度分布：hot=${bucketMap.hot || 0} / potential=${bucketMap.potential || 0} / cold=${bucketMap.cold || 0} / stable=${bucketMap.stable || 0}
- 全库指标（上架款）：平均热度=${metrics.avg_hot} 平均冷门风险=${metrics.avg_cold} 平均转化率=${metrics.avg_conv}
- 总曝光=${metrics.total_view} 总试戴=${metrics.total_tryon} 总确认=${metrics.total_confirm}
- 推荐位：${slots.map(s => `P${s.position}=${s.styleName || '空'}`).join(' / ')}`
}

function buildSystemContent(mode, modeHint, opsContext) {
  const aggCtx = buildAggContext()
  if (mode === 'chat') {
    return modeHint || CHAT_SYSTEM
  }
  if (mode === 'insight') {
    return (modeHint || INSIGHT_SYSTEM) + '\n\n' + aggCtx
  }
  if (mode === 'action') {
    return ACTION_STATIC + '\n\n' + aggCtx
  }
  return CHAT_SYSTEM
}

app.post('/api/ops-deepseek-chat', async (req, res) => {
  try {
    const { message, history = [], opsContext = {}, mode = 'chat', modeHint = '' } = req.body

    const systemContent = buildSystemContent(mode, modeHint, opsContext)

    // Chat 模式保留较短历史；Insight/Action 保留更多
    const historyLimit = mode === 'chat' ? 6 : 10

    const messages = [
      { role: 'system', content: systemContent },
      ...history.slice(-historyLimit),
      { role: 'user', content: message }
    ]

    const temperature = mode === 'chat' ? 0.8 : 0.4

    const resp = await fetch(`${DEEPSEEK_BASE_URL}/chat/completions`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${DEEPSEEK_API_KEY}`
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages,
        temperature,
        max_tokens: mode === 'chat' ? 800 : 2000
      })
    })

    if (!resp.ok) {
      const err = await resp.text()
      console.error('[DeepSeek]', resp.status, err.slice(0, 200))
      return res.status(502).json({ error: `DeepSeek API 错误: ${resp.status}` })
    }

    const data = await resp.json()
    const raw = data.choices?.[0]?.message?.content || ''

    // Action 模式：解析 JSON 格式回复，提取 reply + ops
    if (mode === 'action') {
      try {
        // 策略1：直接整体解析
        let jsonStr = raw.replace(/^```json\s*/i, '').replace(/^```\s*/i, '').replace(/```\s*$/,'').trim()
        let parsed = null
        try {
          parsed = JSON.parse(jsonStr)
        } catch {
          // 策略2：从第一个 { 到最后一个 } 截取（处理前后有正文的情况）
          const start = raw.indexOf('{')
          const end = raw.lastIndexOf('}')
          if (start !== -1 && end > start) {
            try {
              parsed = JSON.parse(raw.slice(start, end + 1))
            } catch { /* 继续降级 */ }
          }
        }
        if (parsed) {
          return res.json({ reply: parsed.reply || '', ops: parsed.ops || [] })
        }
        // 降级：无法解析，当纯文字处理
        return res.json({ reply: raw, ops: [] })
      } catch {
        return res.json({ reply: raw, ops: [] })
      }
    }

    res.json({ reply: raw })
  } catch (e) {
    console.error('[DeepSeek] 异常:', e.message)
    res.status(500).json({ error: e.message })
  }
})

// Parse CSV utility
function parseCSV(filePath) {
  const lines = fs.readFileSync(filePath, 'utf-8').replace(/^﻿/, '').trim().split('\n')
  const headers = lines[0].split(',')
  return lines.slice(1).map(line => {
    const vals = line.split(',')
    const obj = {}
    headers.forEach((h, i) => { obj[h.trim()] = vals[i]?.trim() ?? '' })
    return obj
  })
}

// Load daily CSV with hot-reload on file change
const DAILY_CSV = path.join(SIM_DIR, 'xhs_simulated_nail_style_daily_metrics.csv')
const WEEKLY_CSV = path.join(SIM_DIR, 'xhs_simulated_nail_style_weekly_metrics.csv')

let dailyRows = []
let weeklyRows = []

function reloadCSV() {
  try {
    const newDaily = parseCSV(DAILY_CSV)
    const newWeekly = parseCSV(WEEKLY_CSV)
    dailyRows = newDaily
    weeklyRows = newWeekly
    console.log(`[reload] ${dailyRows.length} daily rows, ${weeklyRows.length} weekly rows`)
  } catch (e) { console.warn('[reload] CSV load failed:', e.message) }
}

reloadCSV()

// Watch for changes (debounced 500ms to avoid double-fire)
let reloadTimer = null
for (const f of [DAILY_CSV, WEEKLY_CSV]) {
  fs.watch(f, () => {
    clearTimeout(reloadTimer)
    reloadTimer = setTimeout(reloadCSV, 500)
  })
}

// /api/xhs-style-trend?styleId=xxx&days=30
app.get('/api/xhs-style-trend', (req, res) => {
  const { styleId, days = '30' } = req.query
  if (!styleId) return res.status(400).json({ error: 'styleId required' })

  const dataset = loadJson(path.join(DATA_DIR, 'xhs-style-dataset.enriched.json'))
  const styleMeta = dataset.styles.find(s => s.id === styleId) || {}

  const nDays = parseInt(days) || 30
  const rows = dailyRows
    .filter(r => r.style_id === styleId)
    .slice(-nDays)
    .map(r => ({
      date: r.date,
      view_uv: +r.view_uv || 0,
      detail_uv: +r.detail_uv || 0,
      tryon_uv: +r.tryon_uv || 0,
      tryon_result_uv: +r.tryon_result_uv || 0,
      want_uv: +r.want_uv || 0,
      total_confirm_uv: +r.total_confirm_uv || 0,
      true_state: r.true_state || 'Stable'
    }))

  const wRows = weeklyRows
    .filter(r => r.style_id === styleId)
    .slice(-8)
    .map(r => ({
      week_idx:         +r.week_idx || 0,
      week:             r.week_label || r.week_start || r.date || `W${r.week_idx || ''}`,
      view_uv:          +r.view_uv || 0,
      tryon_uv:         +r.tryon_uv || 0,
      want_uv:          +r.want_uv || 0,
      total_confirm_uv: +r.total_confirm_uv || 0,
      hot_score:        Math.round((+r.hot_score || 0) * 100),
      cold_risk_score:  Math.round((+r.cold_risk_score || 0) * 100),
      growth_score:     Math.round((+r.growth_score || 0) * 100),
      label:            r.label || r.true_state || 'Stable'
    }))

  res.json({
    styleId,
    styleName: styleMeta.name || styleMeta.rawTitle || styleId,
    image: styleMeta.image || '',
    primaryTag: styleMeta.primaryTag || '',
    secondaryTag: styleMeta.secondaryTag || '',
    daily: rows,
    weekly: wRows,
    summary: {
      totalViews: rows.reduce((s, r) => s + r.view_uv, 0),
      totalTryons: rows.reduce((s, r) => s + r.tryon_uv, 0),
      totalWants: rows.reduce((s, r) => s + r.want_uv, 0),
      totalConfirms: rows.reduce((s, r) => s + r.total_confirm_uv, 0)
    }
  })
})

// /api/xhs-style-compare?styleIds=id1,id2&metric=view_uv&days=30
app.get('/api/xhs-style-compare', (req, res) => {
  const { styleIds = '', metric = 'view_uv', days = '30' } = req.query
  const ids = styleIds.split(',').filter(Boolean)
  if (!ids.length) return res.status(400).json({ error: 'styleIds required' })

  const dataset = loadJson(path.join(DATA_DIR, 'xhs-style-dataset.enriched.json'))
  const styleMap = new Map(dataset.styles.map(s => [s.id, s]))
  const nDays = parseInt(days) || 30

  // Collect all dates from first style as x-axis
  const firstRows = dailyRows.filter(r => r.style_id === ids[0]).slice(-nDays)
  const dates = firstRows.map(r => r.date)

  // 派生比率指标的分子/分母映射
  const RATE_MAP = {
    want_per_view:       ['want_uv',         'view_uv'],
    confirm_per_view:    ['total_confirm_uv', 'view_uv'],
    confirm_per_want:    ['total_confirm_uv', 'want_uv'],
    confirm_per_tryon:   ['total_confirm_uv', 'tryon_result_uv'],
  }
  const rateFields = RATE_MAP[metric]

  const series = ids.map(id => {
    const s = styleMap.get(id) || {}
    const rows = dailyRows.filter(r => r.style_id === id).slice(-nDays)
    const dateMap = new Map(rows.map(r => {
      let val
      if (rateFields) {
        const [num, den] = rateFields
        const n = +r[num] || 0
        const d = +r[den] || 0
        val = d > 0 ? +(n / d).toFixed(4) : null
      } else {
        val = +r[metric] || 0
      }
      return [r.date, val]
    }))
    return {
      styleId: id,
      styleName: s.name || s.rawTitle || id,
      data: dates.map(d => dateMap.get(d) ?? null)
    }
  })

  res.json({ dates, metric, series })
})

// ── Styles Database API ──────────────────────────────────────────────────────

function parseStyleRow(row) {
  if (!row) return null
  return {
    ...row,
    is_promoted: !!row.is_promoted,
    is_cold_start: !!row.is_cold_start,
    crawled: !!row.crawled,
    makeable: !!row.makeable,
    tags_style: JSON.parse(row.tags_style || '[]'),
    tags_color: JSON.parse(row.tags_color || '[]'),
    tags_season: JSON.parse(row.tags_season || '[]'),
    tags_shape: JSON.parse(row.tags_shape || '[]'),
  }
}

// GET /api/styles?status=&bucket=&q=&page=1&pageSize=20
app.get('/api/styles', (req, res) => {
  const { status, bucket, q, page = '1', pageSize = '20' } = req.query
  let where = 'WHERE 1=1'
  const params = []
  if (status) { where += ' AND status = ?'; params.push(status) }
  if (bucket) { where += ' AND recommend_bucket = ?'; params.push(bucket) }
  if (q) { where += ' AND (name LIKE ? OR category LIKE ?)'; params.push(`%${q}%`, `%${q}%`) }

  const total = stylesDb.prepare(`SELECT COUNT(*) as n FROM styles ${where}`).get(...params).n
  const offset = (parseInt(page) - 1) * parseInt(pageSize)
  const rows = stylesDb.prepare(
    `SELECT * FROM styles ${where} ORDER BY hot_score DESC, xhs_likes DESC LIMIT ? OFFSET ?`
  ).all(...params, parseInt(pageSize), offset)

  res.json({ total, page: parseInt(page), pageSize: parseInt(pageSize), rows: rows.map(parseStyleRow) })
})

// GET /api/styles/hot-rank?limit=10  (must be before /:id)
app.get('/api/styles/hot-rank', (req, res) => {
  const limit = parseInt(req.query.limit) || 10
  const rows = stylesDb.prepare(`
    SELECT id, name, recommend_bucket, hot_score, cold_risk_score, tryon_uv, confirm_uv, tryon_confirm_rate, status
    FROM styles ORDER BY hot_score DESC LIMIT ?
  `).all(limit)
  res.json({ rows, count: rows.length })
})

// GET /api/styles/cold-risk?threshold=0.6&limit=10  (must be before /:id)
app.get('/api/styles/cold-risk', (req, res) => {
  const threshold = parseFloat(req.query.threshold) || 0.6
  const limit = parseInt(req.query.limit) || 10
  const rows = stylesDb.prepare(`
    SELECT id, name, recommend_bucket, hot_score, cold_risk_score, view_uv, tryon_uv, status
    FROM styles WHERE cold_risk_score >= ? ORDER BY cold_risk_score DESC LIMIT ?
  `).all(threshold, limit)
  res.json({ rows, count: rows.length })
})

// GET /api/styles/:id
// GET /api/styles/stats — summary counts by status and bucket  (before /:id)
app.get('/api/styles/stats', (req, res) => {
  const byStatus = stylesDb.prepare(`SELECT status, COUNT(*) as n FROM styles GROUP BY status`).all()
  const byBucket = stylesDb.prepare(`SELECT recommend_bucket, COUNT(*) as n FROM styles GROUP BY recommend_bucket`).all()
  res.json({ byStatus, byBucket, total: stylesDb.prepare('SELECT COUNT(*) as n FROM styles').get().n })
})

// POST /api/styles/batch-status  { ids: [], status: '' }  (before /:id)
app.post('/api/styles/batch-status', (req, res) => {
  const { ids, status } = req.body
  if (!Array.isArray(ids) || !ids.length) return res.status(400).json({ error: 'ids required' })
  const allowed = ['published', 'unpublished', 'archived', 'hidden']
  if (!allowed.includes(status)) return res.status(400).json({ error: 'invalid status' })
  const stmt = stylesDb.prepare(`UPDATE styles SET status = ?, updated_at = datetime('now') WHERE id = ?`)
  const run = stylesDb.transaction(() => ids.forEach(id => stmt.run(status, id)))
  run()
  res.json({ ok: true, affected: ids.length, status })
})

// POST /api/styles/query — universal query  (before /:id)
app.post('/api/styles/query', (req, res) => {
  const ALLOWED_FIELDS = new Set([
    'id','style_code','name','description','author','source_url','cover_image',
    'status','is_promoted','is_cold_start','recommend_bucket','trend_label',
    'listed_at','unpublished_at','price','makeable',
    'hot_score','cold_risk_score','growth_score','view_uv','tryon_uv','want_uv',
    'confirm_uv','tryon_confirm_rate',
    'xhs_likes','xhs_saves','xhs_comments','xhs_shares',
    'category','primary_tag','secondary_tag','tags_style','tags_color','tags_season','tags_shape',
    'crawled','created_at','updated_at','thumb','accent','nail_gradient'
  ])
  const OP_MAP = { eq:'=', ne:'!=', gt:'>', lt:'<', gte:'>=', lte:'<=', like:'LIKE', in:'IN' }
  const { filters = [], sort, limit = 50, fields = [] } = req.body
  const where = []
  const params = []
  for (const f of filters) {
    if (!ALLOWED_FIELDS.has(f.field)) continue
    const sqlOp = OP_MAP[f.op]
    if (!sqlOp) continue
    if (f.op === 'in') {
      if (!Array.isArray(f.value) || !f.value.length) continue
      where.push(`${f.field} IN (${f.value.map(() => '?').join(',')})`)
      params.push(...f.value)
    } else if (f.op === 'like') {
      where.push(`${f.field} LIKE ?`)
      params.push(`%${f.value}%`)
    } else {
      where.push(`${f.field} ${sqlOp} ?`)
      params.push(f.value)
    }
  }
  const selectCols = (fields.length ? fields.filter(f => ALLOWED_FIELDS.has(f)) : ['*']).join(', ') || '*'
  let sql = `SELECT ${selectCols} FROM styles`
  if (where.length) sql += ` WHERE ${where.join(' AND ')}`
  if (sort && ALLOWED_FIELDS.has(sort.field)) {
    sql += ` ORDER BY ${sort.field} ${sort.dir === 'asc' ? 'ASC' : 'DESC'}`
  }
  sql += ` LIMIT ${Math.min(parseInt(limit) || 50, 200)}`
  try {
    const rows = stylesDb.prepare(sql).all(...params)
    res.json({ rows, count: rows.length })
  } catch (e) {
    res.status(400).json({ error: e.message })
  }
})

// GET /api/styles/:id
app.get('/api/styles/:id', (req, res) => {
  const row = stylesDb.prepare('SELECT * FROM styles WHERE id = ?').get(req.params.id)
  if (!row) return res.status(404).json({ error: 'not found' })
  res.json(parseStyleRow(row))
})

// PATCH /api/styles/:id/status  { status: 'published'|'unpublished'|'archived' }
app.patch('/api/styles/:id/status', (req, res) => {
  const { status } = req.body
  const allowed = ['published', 'unpublished', 'archived', 'hidden', 'draft']
  if (!allowed.includes(status)) return res.status(400).json({ error: `status must be one of ${allowed.join('/')}` })
  const extra = status === 'unpublished' ? ", unpublished_at = datetime('now')" : ''
  const info = stylesDb.prepare(
    `UPDATE styles SET status = ?, updated_at = datetime('now')${extra} WHERE id = ?`
  ).run(status, req.params.id)
  if (!info.changes) return res.status(404).json({ error: 'not found' })
  res.json({ ok: true, id: req.params.id, status })
})

// PATCH /api/styles/:id  — update any writable fields
app.patch('/api/styles/:id', (req, res) => {
  const allowed = ['name', 'description', 'price', 'is_promoted', 'recommend_bucket', 'category', 'tags_style', 'tags_color', 'tags_season', 'tags_shape']
  const updates = []
  const vals = []
  for (const key of allowed) {
    if (key in req.body) {
      const v = ['tags_style','tags_color','tags_season','tags_shape'].includes(key)
        ? JSON.stringify(req.body[key])
        : req.body[key]
      updates.push(`${key} = ?`)
      vals.push(v)
    }
  }
  if (!updates.length) return res.status(400).json({ error: 'no valid fields' })
  vals.push(req.params.id)
  stylesDb.prepare(`UPDATE styles SET ${updates.join(', ')}, updated_at = datetime('now') WHERE id = ?`).run(...vals)
  res.json({ ok: true, id: req.params.id })
})

// ── 推荐位管理（8坑位一轮）─────────────────────────────────────

const SLOT_TYPE_LABEL = { hot: '热门', potential: '潜力', cold: '冷门观察', adaptive: '用户自适应' }
const SLOT_TYPE_COLOR = { hot: '#ff6b9d', potential: '#36cfc9', cold: '#faad14', adaptive: '#722ed1' }

// 策略定义：每套策略 8 个坑位的 slot_type 分配
const STRATEGY_SLOT_PLANS = {
  hot_first:    ['hot','hot','potential','adaptive','hot','potential','adaptive','cold'],
  potential_up: ['hot','potential','potential','adaptive','potential','adaptive','hot','cold'],
  cold_watch:   ['hot','cold','potential','adaptive','cold','adaptive','potential','hot'],
  adaptive_max: ['adaptive','hot','adaptive','potential','adaptive','hot','adaptive','cold'],
  custom:       null  // 自定义时由前端传入
}

/**
 * 候选池视图（已在 DB 中定义，status='published' 已过滤，分数降序）：
 *   v_pool_hot      → hot_score DESC
 *   v_pool_potential→ growth_score DESC
 *   v_pool_cold     → cold_risk_score DESC
 *   v_pool_adaptive → tryon_confirm_rate DESC（基础兜底，待接入用户偏好打分）
 *
 * 兜底链（候选池耗尽时按序降级）：
 *   hot      → v_pool_hot → v_pool_potential → v_pool_adaptive
 *   potential→ v_pool_potential → v_pool_hot → v_pool_adaptive
 *   cold     → v_pool_cold → v_pool_adaptive（不走热门，避免好款浪费在观察位）
 *   adaptive → keyword 匹配 → v_pool_adaptive → v_pool_hot
 */
function pickStyleForSlot(slotType, excludeIds = [], intentKeywords = '') {
  const ex = excludeIds.length
    ? `WHERE id NOT IN (${excludeIds.map(() => '?').join(',')})`
    : ''

  // 从指定候选池取第一个未用款
  function fromPool(view) {
    return stylesDb.prepare(`SELECT id FROM ${view} ${ex} LIMIT 1`).get(...excludeIds)
  }

  if (slotType === 'hot')
    return fromPool('v_pool_hot')
        || fromPool('v_pool_potential')   // 兜底：增长最快的潜力款
        || fromPool('v_pool_adaptive')    // 兜底：任意高转化在架款

  if (slotType === 'potential')
    return fromPool('v_pool_potential')
        || fromPool('v_pool_hot')         // 兜底：热门款
        || fromPool('v_pool_adaptive')

  if (slotType === 'cold')
    return fromPool('v_pool_cold')
        || fromPool('v_pool_adaptive')    // 冷门位不走热门兜底

  // adaptive：关键词多维匹配 → 候选池兜底
  // TODO: 接入用户端 stylePref/typePref/shapePref/seasonPref 后替换为多维打分 SQL
  if (intentKeywords) {
    const ex2 = excludeIds.length ? `AND id NOT IN (${excludeIds.map(() => '?').join(',')})` : ''
    const kws = intentKeywords.split(/[，,\s]+/).filter(Boolean)
    for (const kw of kws) {
      const row = stylesDb.prepare(`
        SELECT id FROM styles WHERE status='published'
        AND (name LIKE ? OR category LIKE ? OR tags_style LIKE ?
             OR tags_color LIKE ? OR primary_tag LIKE ?) ${ex2}
        ORDER BY tryon_confirm_rate DESC LIMIT 1
      `).get(...Array(5).fill(`%${kw}%`), ...excludeIds)
      if (row) return row
    }
  }
  return fromPool('v_pool_adaptive')
      || fromPool('v_pool_hot')
}

// GET /api/recommend-slots — 返回8个坑位完整信息（JOIN styles）
app.get('/api/recommend-slots', (req, res) => {
  const slots = stylesDb.prepare(`
    SELECT rs.position, rs.slot_type, rs.style_id, rs.strategy_id,
           rs.reason, rs.is_manual, rs.locked, rs.updated_at, rs.updated_by,
           s.name, s.cover_image, s.hot_score, s.cold_risk_score, s.growth_score,
           s.view_uv, s.tryon_uv, s.confirm_uv, s.tryon_confirm_rate,
           s.recommend_bucket, s.status, s.price, s.category
    FROM recommend_slots rs
    LEFT JOIN styles s ON s.id = rs.style_id
    ORDER BY rs.position
  `).all()
  const map = Object.fromEntries(slots.map(r => [r.position, r]))
  const full = Array.from({ length: 8 }, (_, i) => {
    const r = map[i + 1] || { position: i + 1, slot_type: 'hot', style_id: null, strategy_id: 'hot_first', is_manual: 0, locked: 0 }
    return {
      ...r,
      slotTypeLabel: SLOT_TYPE_LABEL[r.slot_type] || r.slot_type,
      slotTypeColor: SLOT_TYPE_COLOR[r.slot_type] || '#999',
      // 款式存在但已下架 → 标记警告，前端可展示提示
      styleOffline: r.style_id && r.status && r.status !== 'published'
    }
  })
  // 同时返回策略列表
  const strategies = stylesDb.prepare('SELECT * FROM recommend_strategies').all().map(s => ({ ...s, slot_types: JSON.parse(s.slot_types) }))
  // rows 是 slots 的别名，统一所有 $ref 查询结果都用 rows 取数组
  res.json({ slots: full, rows: full, strategies })
})

// GET /api/recommend-strategies — 策略列表
app.get('/api/recommend-strategies', (req, res) => {
  const rows = stylesDb.prepare('SELECT * FROM recommend_strategies').all()
    .map(s => ({ ...s, slot_types: JSON.parse(s.slot_types) }))
  res.json({ rows, count: rows.length })
})

// PUT /api/recommend-strategies/custom — 保存自定义策略的 slot_types 配置
// body: { slotTypes: string[8] }
app.put('/api/recommend-strategies/custom', (req, res) => {
  const { slotTypes } = req.body
  const VALID = new Set(['hot', 'potential', 'cold', 'adaptive'])
  if (!Array.isArray(slotTypes) || slotTypes.length !== 8 || slotTypes.some(t => !VALID.has(t)))
    return res.status(400).json({ error: 'slotTypes 需为8个元素，每个为 hot/potential/cold/adaptive' })

  stylesDb.prepare(`
    UPDATE recommend_strategies SET slot_types = ? WHERE id = 'custom'
  `).run(JSON.stringify(slotTypes))
  res.json({ ok: true, slotTypes })
})

// POST /api/recommend-slots/generate — 按策略自动生成一轮推荐
// body: { strategyId, intentText? }
// 所有策略（含 custom）的 slot_types 均从 recommend_strategies 表读取
app.post('/api/recommend-slots/generate', (req, res) => {
  const { strategyId = 'hot_first', intentText = '' } = req.body
  const strategy = stylesDb.prepare('SELECT slot_types FROM recommend_strategies WHERE id = ?').get(strategyId)
  if (!strategy) return res.status(400).json({ error: '未知策略 ' + strategyId })
  const slotPlan = JSON.parse(strategy.slot_types)

  const usedIds = []
  const reasons = {
    hot:      '热度分高，近期确认率稳定，适合主推位',
    potential:'增长分高，曝光不足，补量放大潜力款',
    cold:     '冷门观察位，验证是封面问题还是需求偏弱',
    adaptive: intentText ? `匹配用户偏好「${intentText.slice(0,20)}」` : '高试戴转化率，个性化匹配'
  }

  const upsert = stylesDb.prepare(`
    INSERT INTO recommend_slots(position, slot_type, style_id, strategy_id, reason, is_manual, locked, updated_at, updated_by)
    VALUES (?,?,?,?,?,0,0,datetime('now'),'ai')
    ON CONFLICT(position) DO UPDATE SET
      slot_type=excluded.slot_type, style_id=excluded.style_id, strategy_id=excluded.strategy_id,
      reason=excluded.reason, is_manual=0, updated_at=excluded.updated_at, updated_by='ai'
    WHERE locked=0
  `)

  const generated = stylesDb.transaction(() => {
    const results = []
    for (let i = 0; i < 8; i++) {
      const pos = i + 1
      // 已锁定的坑位跳过
      const existing = stylesDb.prepare('SELECT locked, style_id FROM recommend_slots WHERE position=?').get(pos)
      if (existing?.locked) { results.push({ position: pos, skipped: true, locked: true }); continue }

      const type = slotPlan[i]
      const picked = pickStyleForSlot(type, usedIds, intentText)
      const styleId = picked?.id || null
      if (styleId) usedIds.push(styleId)
      upsert.run(pos, type, styleId, strategyId, reasons[type])
      results.push({ position: pos, slot_type: type, style_id: styleId })
    }
    return results
  })()

  auditLog('recommend.generate', { strategyId, intentText }, { generated })
  res.json({ ok: true, strategyId, generated })
})

// PUT /api/recommend-slots/:position — 手动换款或改坑位类型
// body: { styleId?, slotType?, reason?, locked? }
app.put('/api/recommend-slots/:position', (req, res) => {
  const pos = parseInt(req.params.position)
  if (pos < 1 || pos > 8) return res.status(400).json({ error: 'position must be 1-8' })
  const { styleId, slotType, reason, locked } = req.body

  const current = stylesDb.prepare('SELECT * FROM recommend_slots WHERE position=?').get(pos)
  const updates = []
  const vals = []
  if (styleId !== undefined) {
    const s = stylesDb.prepare('SELECT id FROM styles WHERE id=?').get(styleId)
    if (!s) return res.status(404).json({ error: 'style not found' })
    updates.push('style_id=?', 'is_manual=1'); vals.push(styleId)
  }
  if (slotType !== undefined) { updates.push('slot_type=?'); vals.push(slotType) }
  if (reason !== undefined)   { updates.push('reason=?'); vals.push(reason) }
  if (locked !== undefined)   { updates.push('locked=?'); vals.push(locked ? 1 : 0) }
  updates.push("updated_at=datetime('now')", "updated_by='operator'")
  vals.push(pos)

  if (current) {
    stylesDb.prepare(`UPDATE recommend_slots SET ${updates.join(',')} WHERE position=?`).run(...vals)
  } else {
    stylesDb.prepare(`
      INSERT INTO recommend_slots(position,slot_type,style_id,strategy_id,reason,is_manual,locked,updated_at,updated_by)
      VALUES(?,?,?,?,?,1,0,datetime('now'),'operator')
    `).run(pos, slotType || 'hot', styleId || null, 'custom', reason || '手动调整', )
  }
  auditLog('recommend.set', { position: pos, styleId, slotType }, { ok: true })
  res.json({ ok: true, position: pos })
})

// POST /api/recommend-slots/swap-by-style — 按款式ID互换（只换 style_id，slot_type 保持原位不动）
app.post('/api/recommend-slots/swap-by-style', (req, res) => {
  const { styleIdA, styleIdB } = req.body
  if (!styleIdA || !styleIdB) return res.status(400).json({ error: 'styleIdA and styleIdB required' })
  const rowA = stylesDb.prepare('SELECT * FROM recommend_slots WHERE style_id=?').get(styleIdA)
  const rowB = stylesDb.prepare('SELECT * FROM recommend_slots WHERE style_id=?').get(styleIdB)
  if (!rowA) return res.status(404).json({ error: `styleId ${styleIdA} 不在推荐位中` })
  if (!rowB) return res.status(404).json({ error: `styleId ${styleIdB} 不在推荐位中` })
  const update = stylesDb.prepare(`
    UPDATE recommend_slots SET style_id=?, is_manual=1, updated_at=datetime('now'), updated_by='operator'
    WHERE position=?
  `)
  stylesDb.transaction(() => {
    update.run(styleIdB, rowA.position)
    update.run(styleIdA, rowB.position)
  })()
  auditLog('recommend.swapStyle', { styleIdA, styleIdB, posA: rowA.position, posB: rowB.position }, { ok: true })
  res.json({ ok: true, posA: rowA.position, posB: rowB.position })
})

// POST /api/recommend-slots/swap — 按坑位编号交换款式（只换 style_id，slot_type 保持原位不动）
app.post('/api/recommend-slots/swap', (req, res) => {
  const { positionA, positionB } = req.body
  if (!positionA || !positionB) return res.status(400).json({ error: 'positionA and positionB required' })
  const a = stylesDb.prepare('SELECT * FROM recommend_slots WHERE position=?').get(positionA)
  const b = stylesDb.prepare('SELECT * FROM recommend_slots WHERE position=?').get(positionB)
  const update = stylesDb.prepare(`
    UPDATE recommend_slots SET style_id=?, is_manual=1, updated_at=datetime('now'), updated_by='operator'
    WHERE position=?
  `)
  stylesDb.transaction(() => {
    update.run(b?.style_id ?? null, positionA)
    update.run(a?.style_id ?? null, positionB)
  })()
  auditLog('recommend.swapPos', { positionA, positionB }, { ok: true })
  res.json({ ok: true })
})

// DELETE /api/recommend-slots — 清空全部8个坑位（保留 slot_type 和策略配置）
app.delete('/api/recommend-slots', (req, res) => {
  stylesDb.prepare(`UPDATE recommend_slots SET style_id=NULL, updated_at=datetime('now'), updated_by='operator'`).run()
  auditLog('recommend.clearAll', {}, { ok: true })
  res.json({ ok: true })
})

// DELETE /api/recommend-slots/:position — 清空坑位
app.delete('/api/recommend-slots/:position', (req, res) => {
  const pos = parseInt(req.params.position)
  if (pos < 1 || pos > 8) return res.status(400).json({ error: 'position must be 1-8' })
  stylesDb.prepare(`UPDATE recommend_slots SET style_id=NULL, updated_at=datetime('now'), updated_by='operator' WHERE position=?`).run(pos)
  auditLog('recommend.clear', { position: pos }, { ok: true })
  res.json({ ok: true, position: pos })
})

// POST /api/recommend-slots/:position/refresh — 单槽重新选款
// 保持原 slot_type，从候选池排除已用款式重新抓一个（已锁定则报错）
app.post('/api/recommend-slots/:position/refresh', (req, res) => {
  const pos = parseInt(req.params.position)
  if (pos < 1 || pos > 8) return res.status(400).json({ error: 'position must be 1-8' })
  const slot = stylesDb.prepare('SELECT * FROM recommend_slots WHERE position=?').get(pos)
  if (!slot) return res.status(404).json({ error: '坑位不存在，请先生成一轮推荐' })
  if (slot.locked) return res.status(400).json({ error: `P${pos} 已锁定，请先解锁再刷新` })

  // 排除当前8个坑位已有的款式（不能重复）
  const allUsed = stylesDb.prepare('SELECT style_id FROM recommend_slots WHERE style_id IS NOT NULL AND position!=?').all(pos).map(r => r.style_id)
  const picked = pickStyleForSlot(slot.slot_type, allUsed, '')
  if (!picked) return res.status(404).json({ error: `${slot.slot_type} 候选池已无可用款式` })

  stylesDb.prepare(`UPDATE recommend_slots SET style_id=?, is_manual=0, updated_at=datetime('now'), updated_by='ai' WHERE position=?`).run(picked.id, pos)
  auditLog('recommend.refreshSlot', { position: pos, oldStyleId: slot.style_id, newStyleId: picked.id }, { ok: true })
  res.json({ ok: true, position: pos, oldStyleId: slot.style_id, newStyleId: picked.id })
})

// POST /api/recommend-slots/fill-empty — 补全所有 style_id=NULL 的空坑位
// 锁定坑位也跳过；已有款式坑位不动
app.post('/api/recommend-slots/fill-empty', (req, res) => {
  const { intentText = '' } = req.body
  const emptySlots = stylesDb.prepare(`SELECT * FROM recommend_slots WHERE style_id IS NULL AND locked=0 ORDER BY position`).all()
  if (!emptySlots.length) return res.json({ ok: true, filled: [] })

  const usedIds = stylesDb.prepare('SELECT style_id FROM recommend_slots WHERE style_id IS NOT NULL').all().map(r => r.style_id)
  const filled = stylesDb.transaction(() => {
    const results = []
    for (const slot of emptySlots) {
      const picked = pickStyleForSlot(slot.slot_type, usedIds, intentText)
      if (picked) {
        usedIds.push(picked.id)
        stylesDb.prepare(`UPDATE recommend_slots SET style_id=?, is_manual=0, updated_at=datetime('now'), updated_by='ai' WHERE position=?`).run(picked.id, slot.position)
        results.push({ position: slot.position, slot_type: slot.slot_type, style_id: picked.id })
      } else {
        results.push({ position: slot.position, slot_type: slot.slot_type, style_id: null, failed: true })
      }
    }
    return results
  })()
  auditLog('recommend.fillEmpty', { intentText }, { filled })
  res.json({ ok: true, filled })
})

// POST /api/recommend-slots/batch-lock — 批量锁定
// body: { positions: [1,2,3] }
app.post('/api/recommend-slots/batch-lock', (req, res) => {
  const { positions } = req.body
  if (!Array.isArray(positions) || !positions.length) return res.status(400).json({ error: 'positions[] required' })
  const valid = positions.filter(p => p >= 1 && p <= 8)
  stylesDb.transaction(() => {
    valid.forEach(p => stylesDb.prepare(`UPDATE recommend_slots SET locked=1, updated_at=datetime('now'), updated_by='operator' WHERE position=?`).run(p))
  })()
  auditLog('recommend.batchLock', { positions: valid }, { ok: true })
  res.json({ ok: true, locked: valid })
})

// POST /api/recommend-slots/batch-unlock — 批量解锁
app.post('/api/recommend-slots/batch-unlock', (req, res) => {
  const { positions } = req.body
  if (!Array.isArray(positions) || !positions.length) return res.status(400).json({ error: 'positions[] required' })
  const valid = positions.filter(p => p >= 1 && p <= 8)
  stylesDb.transaction(() => {
    valid.forEach(p => stylesDb.prepare(`UPDATE recommend_slots SET locked=0, updated_at=datetime('now'), updated_by='operator' WHERE position=?`).run(p))
  })()
  auditLog('recommend.batchUnlock', { positions: valid }, { ok: true })
  res.json({ ok: true, unlocked: valid })
})

// GET /api/recommend-slots/find-style/:styleId — 查某款式当前在哪个坑位
app.get('/api/recommend-slots/find-style/:styleId', (req, res) => {
  const styleId = parseInt(req.params.styleId)
  const slot = stylesDb.prepare(`
    SELECT rs.*, s.name, s.cover_image, s.hot_score
    FROM recommend_slots rs
    LEFT JOIN styles s ON s.id = rs.style_id
    WHERE rs.style_id = ?
  `).get(styleId)
  res.json({ found: !!slot, slot: slot || null })
})

// GET /api/recommend-slots/locked — 查所有锁定坑位
app.get('/api/recommend-slots/locked', (req, res) => {
  const rows = stylesDb.prepare(`
    SELECT rs.position, rs.locked, rs.slot_type, rs.style_id, s.name
    FROM recommend_slots rs
    LEFT JOIN styles s ON s.id = rs.style_id
    ORDER BY rs.position
  `).all()
  const locked = rows.filter(r => r.locked)
  res.json({ rows, lockedCount: locked.length, lockedPositions: locked.map(r => r.position) })
})

// ── 查询类 ────────────────────────────────────────────────────

// GET /api/audit-log?limit=20
app.get('/api/audit-log', (req, res) => {
  const limit = parseInt(req.query.limit) || 20
  const rows = stylesDb.prepare('SELECT * FROM audit_log ORDER BY id DESC LIMIT ?').all(limit)
    .map(r => ({ ...r, params: JSON.parse(r.params || '{}'), result: JSON.parse(r.result || '{}') }))
  res.json({ rows, count: rows.length })
})

// POST /api/audit-log  { op, params, result }
app.post('/api/audit-log', (req, res) => {
  const { op, params, result } = req.body
  if (!op) return res.status(400).json({ error: 'op required' })
  auditLog(op, params || {}, result || {})
  res.json({ ok: true })
})

app.listen(PORT, () => {
  console.log(`Mock API server running at http://localhost:${PORT}`)
  console.log('Data: simulation from', SIM_DIR)
  console.log('Styles DB:', DB_PATH)
})
